"""
Generate print-ready DICT_4X4_50 ArUco markers for URC 2026 missions.

Outputs a PDF with one page per mission group at exact physical sizes:
  - Page 1: Autonomous Navigation — Start gate  (ID  0)  20 x 20 cm  [1-cell white border]
  - Page 2: Autonomous Navigation — Nav post 1  (ID  1)  20 x 20 cm  [1-cell white border]
  - Page 3: Autonomous Navigation — Nav post 2  (ID  2)  20 x 20 cm  [1-cell white border]
  - Page 4: Equipment Servicing — Keyboard corners  (IDs 20-23)  2 x 2 cm  [1-cell white border assumed]
  - Page 5: Equipment Servicing — USB-C slot corners  (IDs 30-33)  1 x 1 cm  [1-cell white border assumed]

IDs are placeholders synced with aruco_config.yaml — need to confirm with comp

Nav post border is spec'd exactly in the rules:
  DICT_4X4_50 = 4 data + 1 black border = 6 cells; + 1 white border each side = 8 cells
  8 cells × 2.5 cm/cell = 20 cm face  ✓
  The white border is added as padding after generateImageMarker().

Keyboard / USB borders are shown in the rulebook example images but not dimensionally
  specified. This script applies 1-cell white border (same ratio as nav posts) as a
  best guess — update white_border_cells in MISSION_GROUPS if the spec is clarified.

Usage:
    python3 gen_arucomarker.py
    python3 gen_arucomarker.py --output my_markers.pdf --dpi 300

IMPORTANT: Print at EXACTLY 100% scale (disable "fit to page" in your print dialog).
           Verify physical size with a ruler before use.
"""

import argparse
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.backends.backend_pdf import PdfPages


# ---------------------------------------------------------------------------
# Mission marker definitions pulled from aruco_config.yaml
# (marker_id, physical_size_mm, mission_label)
# ---------------------------------------------------------------------------
ARUCO_DICT = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)

# white_border_cells: white quiet-zone cells to add on each side AFTER generateImageMarker()
#   Nav posts: spec'd as exactly 1 cell (2.5 cm) → 8×8 cells × 2.5 cm = 20 cm face
#   Keyboard/USB: 1 cell assumed from rulebook images — update if spec is clarified
MISSION_GROUPS = [
    {
        "name": "Autonomous Navigation — Start Gate",
        "detail": "20×20 cm face  |  ID 0  |  same post design as nav posts; used for initial GNSS alignment  |  print 3 copies for 3-sided post",
        "markers": [(0, 200)],
        "white_border_cells": 1,  # spec'd: 1 cell = 2.5 cm
    },
    {
        "name": "Autonomous Navigation — Post 1",
        "detail": "20×20 cm face  |  ID 1  |  GNSS within 5-10 m, stop within 2 m  |  print 3 copies for 3-sided post",
        "markers": [(1, 200)],
        "white_border_cells": 1,  # spec'd: 1 cell = 2.5 cm
    },
    {
        "name": "Autonomous Navigation — Post 2",
        "detail": "20×20 cm face  |  ID 2  |  GNSS within 10-20 m, stop within 2 m  |  print 3 copies for 3-sided post",
        "markers": [(2, 200)],
        "white_border_cells": 1,  # spec'd: 1 cell = 2.5 cm
    },
    {
        "name": "Equipment Servicing — Keyboard Corners",
        "detail": "2×2 cm face  |  IDs 20-23 (placeholder — confirm with URC)  |  one at each corner of the keyboard",
        "markers": [(20, 20), (21, 20), (22, 20), (23, 20)],
        "white_border_cells": 1,  # assumed from rulebook image — unconfirmed
    },
    {
        "name": "Equipment Servicing — USB-C Slot Corners",
        "detail": "1×1 cm face  |  IDs 30-33 (placeholder — confirm with URC)  |  one at each corner of the USB-C slot",
        "markers": [(30, 10), (31, 10), (32, 10), (33, 10)],
        "white_border_cells": 1,  # assumed from rulebook image — unconfirmed
    },
]

# US Letter page (inches)
PAGE_W = 8.5
PAGE_H = 11.0


def mm_to_in(mm: float) -> float:
    return mm / 25.4


def generate_marker_px(
    marker_id: int, dpi: int, face_mm: float, white_border_cells: int = 0
) -> np.ndarray:
    """Return a grayscale marker image sized to exactly face_mm at the given DPI.

    DICT_4X4_50 markers have 4 data cells + 1 black border = 6 cells total as
    generated by OpenCV. white_border_cells adds that many white-cell-width rows of
    padding on each side (the quiet zone). The overall image is then exactly face_mm
    wide at the printed DPI.

    Nav post spec: face_mm=200, white_border_cells=1
      → 8 total cells × 2.5 cm/cell = 20 cm  ✓
    """
    # total cells across one dimension
    total_cells = 6 + 2 * white_border_cells  # 6 = 4 data + 1 black border each side
    cell_px = max(int(round(mm_to_in(face_mm / total_cells) * dpi)), 4)

    # generate the core 6-cell marker
    marker_px = 6 * cell_px
    img = cv2.aruco.generateImageMarker(ARUCO_DICT, marker_id, marker_px)

    # add white border padding
    if white_border_cells > 0:
        pad = white_border_cells * cell_px
        img = cv2.copyMakeBorder(
            img, pad, pad, pad, pad, cv2.BORDER_CONSTANT, value=255
        )

    return img


def draw_page(pdf: PdfPages, group: dict, dpi: int) -> None:
    """Write one PDF page for a mission group."""
    n = len(group["markers"])
    fig = plt.figure(figsize=(PAGE_W, PAGE_H), dpi=dpi)

    white_border_cells = group.get("white_border_cells", 0)
    size_mm = group["markers"][0][1]  # all markers in a group share the same size
    border_note = ""
    if white_border_cells:
        confirmed = group["name"].startswith("Autonomous")
        border_note = f"  |  {white_border_cells}-cell white border " + (
            "(spec'd: each cell = {:.1f} mm)".format(
                size_mm / (6 + 2 * white_border_cells)
            )
            if confirmed
            else "(assumed from rulebook image — unconfirmed)"
        )

    # --- header: title + detail subtitle (size/border shared by all markers) ---
    fig.text(
        0.5,
        0.970,
        group["name"],
        ha="center",
        va="top",
        fontsize=13,
        fontweight="bold",
    )
    fig.text(
        0.5,
        0.948,
        group["detail"],
        ha="center",
        va="top",
        fontsize=8.5,
        color="#444444",
    )
    fig.text(
        0.5,
        0.926,
        f"Face size: {size_mm}×{size_mm} mm{border_note}",
        ha="center",
        va="top",
        fontsize=8,
        color="#888888",
        style="italic",
    )

    HEADER_TOP = 0.905  # figure fraction where content starts below header
    FOOTER_H = 0.07  # reserved for footer
    LABEL_H = 0.04  # reserved below each marker for the ID label

    usable_h = HEADER_TOP - FOOTER_H - LABEL_H

    # Lay out markers in a single row, centered
    marker_size_in = mm_to_in(size_mm)
    # minimum gap: 0.3 in; scale up for tiny markers so they don't crowd
    gap_in = max(0.3, 0.5 * marker_size_in)

    cell_w_frac = marker_size_in / PAGE_W
    cell_h_frac = marker_size_in / PAGE_H

    # If the row would be wider than the page, scale everything down
    total_w_frac = n * cell_w_frac + (n - 1) * (gap_in / PAGE_W)
    MARGIN = 0.06
    max_w = 1.0 - 2 * MARGIN
    if total_w_frac > max_w:
        scale = max_w / total_w_frac
        cell_w_frac *= scale
        cell_h_frac *= scale
        gap_in *= scale
        total_w_frac = max_w

    start_x = 0.5 - total_w_frac / 2.0
    centre_y = FOOTER_H + LABEL_H + usable_h * 0.5

    for i, (marker_id, _) in enumerate(group["markers"]):
        img = generate_marker_px(marker_id, dpi, size_mm, white_border_cells)

        ax_x = start_x + i * (cell_w_frac + gap_in / PAGE_W)
        ax_y = centre_y - cell_h_frac / 2.0
        ax = fig.add_axes([ax_x, ax_y, cell_w_frac, cell_h_frac])

        ax.imshow(
            img, cmap="gray", vmin=0, vmax=255, interpolation="nearest", aspect="equal"
        )
        ax.axis("off")

        # Red border — verify printed size with a ruler
        rect = patches.FancyBboxPatch(
            (0, 0),
            1,
            1,
            boxstyle="square,pad=0",
            linewidth=1.5,
            edgecolor="red",
            facecolor="none",
            transform=ax.transAxes,
            clip_on=False,
        )
        ax.add_patch(rect)

        # "ID XX" label centred below each marker, sized to fit the marker width
        label_fontsize = max(5, min(10, cell_w_frac * PAGE_W * 72 * 0.35))
        fig.text(
            ax_x + cell_w_frac / 2,
            ax_y - 0.012,
            f"ID {marker_id}",
            ha="center",
            va="top",
            fontsize=label_fontsize,
            fontweight="bold",
        )

    # --- footer ---
    fig.text(
        0.5,
        0.025,
        "⚠  Print at EXACTLY 100% scale — disable 'Fit to Page' in your print dialog.  "
        "Verify the red border matches the stated size with a ruler before deploying.",
        ha="center",
        va="bottom",
        fontsize=7.5,
        color="red",
        style="italic",
        wrap=True,
    )

    pdf.savefig(fig, dpi=dpi)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate URC 2026 ArUco markers (DICT_4X4_50) as a print-ready PDF"
    )
    parser.add_argument(
        "--output",
        default="aruco_markers_urc2026.pdf",
        help="Output PDF filename (default: aruco_markers_urc2026.pdf)",
    )
    parser.add_argument(
        "--dpi", type=int, default=300, help="Print resolution in DPI (default: 300)"
    )
    args = parser.parse_args()

    with PdfPages(args.output) as pdf:
        for group in MISSION_GROUPS:
            draw_page(pdf, group, args.dpi)

        d = pdf.infodict()
        d["Title"] = "URC 2026 ArUco Markers — DICT_4X4_50"
        d["Subject"] = (
            "Equipment Servicing (keyboard, USB) and Autonomous Navigation (posts)"
        )

    print(f"✓  Saved: {args.output}")
    print(f"   {len(MISSION_GROUPS)} pages:")
    for group in MISSION_GROUPS:
        ids = ", ".join(str(m[0]) for m in group["markers"])
        size = group["markers"][0][1]
        print(f"     {group['name']}  →  IDs [{ids}]  @ {size}×{size} mm")
    print("\n⚠  Print at 100% scale. Verify size with a ruler before use.")


if __name__ == "__main__":
    main()
